### ISSUE TITLE
Branch filter for download artifacts isn't taking effect.

### ISSUE THREAD

**Issue by rsdmike** [sevaa/githubactions#2]
I see the branch property in the `task.json`, but I'm not seeing it in the build editor. I've also tried with YAML mode as well, specifying the `branch:` input however it is not taking effect. Can you take a look?
![image](https://user-images.githubusercontent.com/22204562/177432097-8e04974a-7b0a-4a26-82a4-d1444c947a89.png)
YAML:
``` yaml
- task: sevaalekseyev.githubactions.dlartifacts.DownloadArtifacrs@0
  displayName: 'Get the artifacts from Unit Tests on github.com'
  inputs:
    gh: 'GitHub connection 1'
    repo: 'my-org/my-repo'
    workflow: 'Node.js CI'
    branch: 'main'
```
